const iconNames = [
    "accountbox",
    "activefolder",
    "add",
    "addcirclefilled",
    "addcircleoutline",
    "addtableheader",
    "airplane",
    "aligncenter",
    "alignjustify",
    "alignleft",
    "alignright",
    "arrowback",
    "arrowdown",
    "arrowleft",
    "arrowright",
    "arrowsortdown",
    "arrowsortup",
    "arrowup",
    "attach",
    "back",
    "background",
    "bell",
    "belloutline",
    "blockquote",
    "bmpfile",
    "bold",
    "bookmark",
    "box",
    "bulletlist",
    "calendardateendfilled",
    "calendardateendoutline",
    "calendardatestartfilled",
    "calendardatestartoutline",
    "car",
    "card",
    "cardcontent",
    "cart",
    "cellproperties",
    "chart",
    "chat",
    "chatadd",
    "chatsparklefilled",
    "chatsparkleoutline",
    "check",
    "checklist",
    "checkmarkcircle",
    "chevrondoubleleft",
    "chevrondoubleright",
    "chevrondown",
    "chevronleft",
    "chevronnext",
    "chevronprev",
    "chevronright",
    "chevronup",
    "clear",
    "clearcircle",
    "clearformat",
    "clearsquare",
    "clipboardpastesparkle",
    "clipboardtasklist",
    "clock",
    "close",
    "codeblock",
    "coffee",
    "collapse",
    "color",
    "colordismiss",
    "columnchooser",
    "columnfield",
    "columnproperties",
    "comment",
    "conferenceroomfilled",
    "conferenceroomoutline",
    "contains",
    "contentlayout",
    "copy",
    "csv",
    "cursormove",
    "cursorprohibition",
    "cut",
    "dataarea",
    "datafield",
    "datapie",
    "datatrending",
    "datausage",
    "daterangepicker",
    "decreaseindent",
    "decreaselinespacing",
    "deletecolumn",
    "deleterow",
    "deletetable",
    "description",
    "detailslayout",
    "doc",
    "docfile",
    "docxfile",
    "doesnotcontain",
    "download",
    "dragvertical",
    "dropzone",
    "edit",
    "edittableheader",
    "email",
    "endswith",
    "equal",
    "errorcircle",
    "event",
    "eventall",
    "expand",
    "expandform",
    "export",
    "exportpdf",
    "exportselected",
    "exportxlsx",
    "eyeclose",
    "eyeopen",
    "favorites",
    "fieldchooser",
    "fields",
    "file",
    "fill",
    "filter",
    "find",
    "fixcolumn",
    "fixcolumnleft",
    "fixcolumnright",
    "floppy",
    "folder",
    "font",
    "fontsize",
    "food",
    "formula",
    "fullscreen",
    "gift",
    "globe",
    "greater",
    "greaterorequal",
    "group",
    "groupbycolumn",
    "growfont",
    "handlehorizontal",
    "handlevertical",
    "header",
    "help",
    "hidepanel",
    "hierarchy",
    "home",
    "image",
    "imagethumbnail",
    "imgarlock",
    "imgarunlock",
    "import",
    "importselected",
    "inactivefolder",
    "increaseindent",
    "increaselinespacing",
    "indent",
    "indeterminatestate",
    "info",
    "insertcolumnleft",
    "insertcolumnright",
    "insertrowabove",
    "insertrowbelow",
    "inserttable",
    "isblank",
    "isnotblank",
    "italic",
    "jpgfile",
    "key",
    "less",
    "lessorequal",
    "like",
    "link",
    "lock",
    "login",
    "map",
    "mediumiconslayout",
    "mention",
    "menu",
    "mergecells",
    "message",
    "micfilled",
    "micoutline",
    "minus",
    "money",
    "moon",
    "more",
    "movetofolder",
    "music",
    "newfolder",
    "notequal",
    "optionsfilled",
    "optionsgear",
    "optionsoutline",
    "orderedlist",
    "ordersbox",
    "overflow",
    "packagebox",
    "palette",
    "panelleft",
    "panelright",
    "parentfolder",
    "paste",
    "pasteplaintext",
    "pdffile",
    "percent",
    "photo",
    "photooutline",
    "pin",
    "pinleft",
    "pinmap",
    "pinright",
    "plus",
    "pptfile",
    "pptxfile",
    "preferences",
    "print",
    "product",
    "pulldown",
    "range",
    "ratingfilled",
    "ratingoutline",
    "redo",
    "refresh",
    "remove",
    "rename",
    "repeat",
    "restore",
    "return",
    "revert",
    "rowfield",
    "rowproperties",
    "rtffile",
    "runner",
    "save",
    "search",
    "selectall",
    "send",
    "sendfilled",
    "servicebell",
    "share",
    "showpanel",
    "shrinkfont",
    "smalliconslayout",
    "sortdown",
    "sortdowntext",
    "sorted",
    "sortup",
    "sortuptext",
    "sparkle",
    "spindown",
    "spinleft",
    "spinnext",
    "spinprev",
    "spinright",
    "spinup",
    "splitcells",
    "square",
    "startswith",
    "stickcolumn",
    "stopfilled",
    "stopoutline",
    "strike",
    "subscript",
    "sun",
    "superscript",
    "svgfile",
    "tableproperties",
    "tags",
    "taskcomplete",
    "taskhelpneeded",
    "taskinprogress",
    "taskrejected",
    "taskstop",
    "tel",
    "textdocument",
    "tips",
    "to",
    "today",
    "todo",
    "toolbox",
    "trash",
    "triangledown",
    "triangleleft",
    "triangleright",
    "triangleup",
    "txtfile",
    "underline",
    "undo",
    "unfixcolumn",
    "ungroupcolumn",
    "ungroupallcolumns",
    "unlock",
    "unpin",
    "unselectall",
    "upload",
    "user",
    "variable",
    "verticalalignbottom",
    "verticalaligncenter",
    "verticalaligntop",
    "video",
    "warning",
    "xlsfile",
    "xlsxfile",
    "zoominfilled",
    "zoominoutline",
    "zoomoutfilled",
    "zoomoutoutline",
];

let divs = [];
let externalContainer = $("#external-container");

iconNames.forEach(icon => {
    let div = $("<div class='container'>").append(
        $("<i class='icon dx-icon-" + icon + "'></i>"),
        $("<span class='icon-name'>" + icon + "</span>"),
    );

    externalContainer.append(div);
    
    //console.log(window.getComputedStyle(document.querySelector(`i.icon.dx-icon-${icon}`), '::before').getPropertyValue('content').replace(/["']/g, '').codePointAt(0).toString(16));
});

iconNames.forEach(icon => {
    //console.log(window.getComputedStyle(document.querySelector(`i.icon.dx-icon-${icon}`), '::before').getPropertyValue('content').replace(/["']/g, '').codePointAt(0).toString(16));
})

//

let mainSheet;

for (const sheet of document.styleSheets) {
    if (sheet.href?.includes('fluent')) {
        mainSheet = sheet;
        break;
    }
}

const singleIconStyleRegex = /.dx-icon-([\w]+)::before/
const doubleIconStyleRegex = /.dx-icon-([\w]+)::before, .dx-icon-([\w]+)::before/
const tripleIconStyleRegex = /.dx-icon-([\w]+)::before, .dx-icon-([\w]+)::before, .dx-icon-([\w]+)::before/

let icons = [];

for (let id = 0; id < mainSheet.cssRules.length; id++) {
    const rule = mainSheet.cssRules[id];

    if (rule.selectorText && (rule.selectorText.match(singleIconStyleRegex) && !rule.selectorText.includes(' ') || rule.selectorText.match(doubleIconStyleRegex))) {
        const iconChar = `\\${rule.style.content.replace(/["']/g, '').codePointAt(0).toString(16)}`;
        const iconName = rule.selectorText.split('::')[0].split('-')[2];
        icons.push({id, iconName, iconChar});
    }

    if (rule.selectorText && rule.selectorText.match(doubleIconStyleRegex)) {
        const iconChar = `\\${rule.style.content.replace(/["']/g, '').codePointAt(0).toString(16)}`;
        const iconName = rule.selectorText.split('::')[1].split('-')[2];
        icons.push({id, iconName, iconChar});
    }

    if (rule.selectorText && rule.selectorText.match(tripleIconStyleRegex)) {
        const iconChar = `\\${rule.style.content.replace(/["']/g, '').codePointAt(0).toString(16)}`;
        const iconName = rule.selectorText.split('::')[2].split('-')[2];
        icons.push({id, iconName, iconChar});
    }
}

console.log(`Predefined array: ${iconNames.length}; Dynamic array: ${icons.length}`)

console.log(icons)

$('#grid-container').dxCardView({
    dataSource: icons,
    columns: [{
        dataField: 'id',
        caption: 'Icon',
        cellTemplate(container, rowData) {
            return $(`<i class='icon dx-icon-${rowData.data.iconName}'></i>`)
        },
        fieldValueTemplate(field) {
            return $(`<i class='icon dx-icon-${field.field.card.data.iconName}' style='text-align: center'></i>`)
        },
        alignment: 'center',
    }, {
        dataField: 'iconName',
        caption: 'Name',
        alignment: 'center',
    }, {
        dataField: 'iconChar',
        fieldCaptionTemplate(data) {
            return $('<div>').html('Character<br>Code:');
        },
        alignment: 'center',
    }],
    searchPanel: {
        visible: true,
    },
    scrolling: {
        enabled: true,
    },
    paging: {
        enabled: false,
    },
    height: '1000px',
    cardMinWidth: 240,
})