name: Node.js CI

on: [push, pull_request]

jobs:

  validation:
    name: Validation docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: Validation
        run: npm run validate-docs

  build:
    name: ContentMap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: Generate ContentMaps
        run: npm run generate-content-map

  link:
    runs-on: ubuntu-latest

    name: Check links
    steps:
      - name: Checkout Docs
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: Generate ContentMaps
        run: npm run generate-content-map

      - name: Check links
        run: npm run validate-links
