name: Node.js CI

on: [push, pull_request]

env:
  nodeVersion: 14.x

jobs:

  validation:
    runs-on: ubuntu-latest
    name: Validation docs
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install dependencies
      run: npm install

    - name: Validation
      run: npm run validate-docs

  build:
    runs-on: ubuntu-latest
    name: ContentMap
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install dependencies
      run: npm install

    - name: Generate ContentMaps
      run: npm run generate-content-map

  link:
    runs-on: ubuntu-latest
    name: Check links
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install dependencies
      run: npm install

    - name: Generate ContentMaps
      run: npm run generate-content-map

    - name: Check links
      run: npm run validate-links

  # modules:
  #   runs-on: ubuntu-latest
  #   name: Check modules guide
  #   steps:

  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ env.nodeVersion }}

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Check modules guide
  #     run: npm run validate-modules-guide
