name: Node.js CI

on: [push, pull_request]

env:
  node-version: 12.x

jobs:

  build:
    runs-on: ubuntu-latest
    name: ContentMap
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install dependencies
      run: npm install

    - name: Generate ContentMaps
      run: npm run generate-content-map

  link:
    runs-on: ubuntu-latest
    name: Check links
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install dependencies
      run: npm install

    - name: Generate ContentMaps
      run: npm run generate-content-map

    - name: Check links
      run: npm run update-links-validation
