name: Node.js CI

on: [push, pull_request]

env:
  node-version: 12.x

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare
    steps:

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1

  build:
    runs-on: ubuntu-latest
    name: ContentMap
    needs: [prepare]
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install dependencies
      run: npm install

    - name: Generate ContentMaps
      run: npm run generate-content-map

  link:
    runs-on: ubuntu-latest
    name: Check links
    needs: [prepare]
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install dependencies
      run: npm install

    - name: Generate ContentMaps
      run: npm run generate-content-map

    - name: Check links
      run: npm run update-links-validation
